# Generated by Django 3.0.3 on 2020-06-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20200514_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_or_student',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Student', 'Student'), ('None', 'None')], default='None', max_length=20, null=True),
        ),
    ]
