# Generated by Django 3.0.3 on 2020-06-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_userprofile_company_or_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_or_student',
            new_name='type',
        ),
    ]
