# Generated by Django 3.0.3 on 2020-06-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0004_auto_20200611_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Company', 'Company'), ('Student', 'Student'), ('None', 'None')], default='Company', max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_place', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_range', models.FloatField()),
                ('number_of_employees', models.IntegerField()),
                ('about_company', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Company', 'Company'), ('Student', 'Student'), ('None', 'None')], default='Company', max_length=20, null=True)),
                ('age', models.IntegerField()),
                ('living_area', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('cv', models.FileField(upload_to='cv_files/')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='None', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
