# Generated by Django 3.0.3 on 2020-06-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20200612_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_user',
            name='about_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_user',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_user',
            name='salary_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='living_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
