# Generated by Django 3.0.3 on 2020-06-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20200612_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_user',
            name='type',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Student', 'Student'), ('None', 'None')], default='Student', max_length=20, null=True),
        ),
    ]
