# Generated by Django 3.0.3 on 2020-06-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_auto_20200612_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_user',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companys_logo/'),
        ),
    ]
