# Generated by Django 3.0.3 on 2020-06-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_company_user_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_user',
            name='age',
        ),
        migrations.AddField(
            model_name='student_user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_user',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_user',
            name='practical_experiences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_user',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_user',
            name='specialist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='type',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Student', 'Student'), ('None', 'None')], default='Student', max_length=10, null=True),
        ),
    ]
