# Generated by Django 3.0.3 on 2020-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200612_1816'),
        ('user_auth', '0009_auto_20200612_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_user',
            name='jobs',
            field=models.ManyToManyField(to='website.Job'),
        ),
    ]
