# Generated by Django 3.0.3 on 2020-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_remove_student_user_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_user',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to='std_personal_images/'),
        ),
    ]
