# Generated by Django 3.0.3 on 2020-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_student_user_personal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_user',
            name='type',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Student', 'Student')], default='Company', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='cv',
            field=models.FileField(blank=True, default='std_personal_images/default_personal_image.jpg', null=True, upload_to='std_cv/'),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='type',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Student', 'Student')], default='Student', max_length=10, null=True),
        ),
    ]
