# Generated by Django 3.0.3 on 2020-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_auto_20200613_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='std_cv/'),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='personal_image',
            field=models.ImageField(blank=True, default='std_personal_images/default_personal_image.jpg', null=True, upload_to='std_personal_images/'),
        ),
    ]
