# Generated by Django 3.0.3 on 2020-06-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_auto_20200613_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_user',
            name='cv',
            field=models.FileField(blank=True, default='std_cv/defaut_cv.pdf', null=True, upload_to='std_cv/'),
        ),
    ]
