# Generated by Django 3.0.3 on 2020-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200612_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
