# Generated by Django 3.0.3 on 2020-06-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_remove_student_user_jobs'),
        ('website', '0004_auto_20200612_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Company_user'),
        ),
    ]
