# Generated by Django 3.0.3 on 2020-06-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_auto_20200613_1930'),
        ('website', '0006_auto_20200612_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='students_applyed',
            field=models.ManyToManyField(to='user_auth.Student_user'),
        ),
    ]
