# Generated by Django 3.0.3 on 2020-06-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_auto_20200613_1930'),
        ('website', '0007_job_students_applyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='students_applyed',
            field=models.ManyToManyField(blank=True, null=True, to='user_auth.Student_user'),
        ),
    ]
