# Generated by Django 3.0.3 on 2020-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_auto_20200613_1930'),
        ('website', '0008_auto_20200613_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='students_applyed',
            field=models.ManyToManyField(to='user_auth.Student_user'),
        ),
    ]
