# Generated by Django 3.0.3 on 2020-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_auto_20200613_1930'),
        ('website', '0009_auto_20200613_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='students_choosen',
            field=models.ManyToManyField(related_name='job_requests_created2', to='user_auth.Student_user'),
        ),
        migrations.AlterField(
            model_name='job',
            name='students_applyed',
            field=models.ManyToManyField(related_name='job_requests_created', to='user_auth.Student_user'),
        ),
    ]
