# Generated by Django 3.0.3 on 2020-06-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_auto_20200613_1930'),
        ('website', '0010_auto_20200613_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='students_applyed',
            field=models.ManyToManyField(related_name='job_requests_students_applyed', to='user_auth.Student_user'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='students_choosen',
        ),
        migrations.AddField(
            model_name='job',
            name='students_choosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requests_students_choosen', to='user_auth.Student_user'),
        ),
    ]
